import 'CountryModel.dart';

final List<CountryModel> COUNTRIES = [
  CountryModel("AD", "Andorra", "+376", "EUR"),
  CountryModel("AE", "United Arab Emirates", "+971", "AED"),
  CountryModel("AF", "Afghanistan", "+93", "AFN"),
  CountryModel("AG", "Antigua & Barbuda", "+1", "XCD"),
  CountryModel("AI", "Anguilla", "+1", "XCD"),
  CountryModel("AL", "Albania", "+355", "ALL"),
  CountryModel("AM", "Armenia", "+374", "AMD"),
  CountryModel("AO", "Angola", "+244", "AOA"),
  CountryModel("AQ", "Antarctica", "+672", "USD"),
  CountryModel("AR", "Argentina", "+54", "ARS"),
  CountryModel("AS", "American Samoa", "+1", "USD"),
  CountryModel("AT", "Austria", "+43", "EUR"),
  CountryModel("AU", "Australia", "+61", "AUD"),
  CountryModel("AW", "Aruba", "+297", "AWG"),
  CountryModel("AX", "Åland Islands", "+358", "EUR"),
  CountryModel("AZ", "Azerbaijan", "+994", "AZN"),
  CountryModel("BA", "Bosnia and Herzegovina", "+387", "BAM"),
  CountryModel("BB", "Barbados", "+1", "BBD"),
  CountryModel("BD", "Bangladesh", "+880", "BDT"),
  CountryModel("BE", "Belgium", "+32", "EUR"),
  CountryModel("BF", "Burkina Faso", "+226", "XOF"),
  CountryModel("BG", "Bulgaria", "+359", "BGN"),
  CountryModel("BH", "Bahrain", "+973", "BHD"),
  CountryModel("BI", "Burundi", "+257", "BIF"),
  CountryModel("BJ", "Benin", "+229", "XOF"),
  CountryModel("BL", "Saint Barthelemy", "+590", "EUR"),
  CountryModel("BM", "Bermuda", "+1", "BMD"),
  CountryModel("BN", "Brunei Darussalam", "+673", "BND"),
  CountryModel("BO", "Bolivia", "+591", "BOB"),
  CountryModel("BQ", "Bonaire", "+599", "USD"),
  CountryModel("BR", "Brazil", "+55", "BRL"),
  CountryModel("BS", "Bahamas", "+1", "BSD"),
  CountryModel("BT", "Bhutan", "+975", "BTN"),
  CountryModel("BV", "Bouvet Island", "+47", "NOK"),
  CountryModel("BW", "Botswana", "+267", "BWP"),
  CountryModel("BY", "Belarus", "+375", "BYR"),
  CountryModel("BZ", "Belize", "+501", "BZD"),
  CountryModel("CA", "Canada", "+1", "CAD"),
  CountryModel("CC", "Cocos (Keeling) Islands", "+61", "AUD"),
  CountryModel("CD", "Congo, The Democratic Republic of the", "+243", "CDF"),
  CountryModel("CF", "Central African Republic", "+236", "XAF"),
  CountryModel("CG", "Congo", "+242", "XAF"),
  CountryModel("CH", "Switzerland", "+41", "CHF"),
  CountryModel("CI", "Côte d'Ivoire", "+225", "XOF"),
  CountryModel("CK", "Cook Islands", "+682", "NZD"),
  CountryModel("CL", "Chile", "+56", "CLP"),
  CountryModel("CM", "Cameroon", "+237", "XAF"),
  CountryModel("CN", "China", "+86", "CNY"),
  CountryModel("CO", "Colombia", "+57", "COP"),
  CountryModel("CR", "Costa Rica", "+506", "CRC"),
  CountryModel("CU", "Cuba", "+53", "CUP"),
  CountryModel("CV", "Cabo Verde", "+238", "CVE"),
  CountryModel("CW", "Curacao", "+599", "ANG"),
  CountryModel("CX", "Christmas Island", "+61", "AUD"),
  CountryModel("CY", "Cyprus", "+357", "EUR"),
  CountryModel("CZ", "Czechia", "+420", "CZK"),
  CountryModel("DE", "Germany", "+49", "EUR"),
  CountryModel("DJ", "Djibouti", "+253", "DJF"),
  CountryModel("DK", "Denmark", "+45", "DKK"),
  CountryModel("DM", "Dominica", "+1", "XCD"),
  CountryModel("DO", "Dominican Republic", "+1", "DOP"),
  CountryModel("DZ", "Algeria", "+213", "DZD"),
  CountryModel("EC", "Ecuador", "+593", "USD"),
  CountryModel("EE", "Estonia", "+372", "EUR"),
  CountryModel("EG", "Egypt", "+20", "EGP"),
  CountryModel("EH", "Western Sahara", "+212", "MAD"),
  CountryModel("ER", "Eritrea", "+291", "ERN"),
  CountryModel("ES", "Spain", "+34", "EUR"),
  CountryModel("ET", "Ethiopia", "+251", "ETB"),
  CountryModel("FI", "Finland", "+358", "EUR"),
  CountryModel("FJ", "Fiji", "+679", "FJD"),
  CountryModel("FK", "Falkland Islands [Malvinas]", "+500", "FKP"),
  CountryModel("FM", "Micronesia, Federated States of", "+691", "USD"),
  CountryModel("FO", "Faroe Islands", "+298", "DKK"),
  CountryModel("FR", "France", "+33", "EUR"),
  CountryModel("GA", "Gabon", "+241", "XAF"),
  CountryModel("GB", "United Kingdom", "+44", "GBP"),
  CountryModel("GD", "Grenada", "+1", "XCD"),
  CountryModel("GE", "Georgia", "+995", "GEL"),
  CountryModel("GF", "French Guiana", "+594", "EUR"),
  CountryModel("GG", "Guernsey", "+44", "GGP"),
  CountryModel("GH", "Ghana", "+233", "GHS"),
  CountryModel("GI", "Gibraltar", "+350", "GIP"),
  CountryModel("GL", "Greenland", "+299", "DKK"),
  CountryModel("GM", "Gambia", "+220", "GMD"),
  CountryModel("GN", "Guinea", "+224", "GNF"),
  CountryModel("GP", "Guadeloupe", "+590", "EUR"),
  CountryModel("GQ", "Equatorial Guinea", "+240", "XAF"),
  CountryModel("GR", "Greece", "+30", "EUR"),
  CountryModel(
    "GS",
    "South Georgia and the South Sandwich Islands",
    "+500",
    "GBP",
  ),
  CountryModel("GT", "Guatemala", "+502", "GTQ"),
  CountryModel("GU", "Guam", "+1", "USD"),
  CountryModel("GW", "Guinea-Bissau", "+245", "XOF"),
  CountryModel("GY", "Guyana", "+595", "GYD"),
  CountryModel("HK", "Hong Kong", "+852", "HKD"),
  CountryModel("HM", "Heard Island and McDonald Islands", "+000", "AUD"),
  CountryModel("HN", "Honduras", "+504", "HNL"),
  CountryModel("HR", "Croatia", "+385", "HRK"),
  CountryModel("HT", "Haiti", "+509", "HTG"),
  CountryModel("HU", "Hungary", "+36", "HUF"),
  CountryModel("ID", "Indonesia", "+62", "IDR"),
  CountryModel("IE", "Ireland", "+353", "EUR"),
  CountryModel("IL", "Israel", "+972", "ILS"),
  CountryModel("IM", "Isle of Man", "+44", "GBP"),
  CountryModel("IN", "India", "+91", "INR"),
  CountryModel("IO", "British Indian Ocean Territory", "+246", "USD"),
  CountryModel("IQ", "Iraq", "+964", "IQD"),
  CountryModel("IR", "Iran, Islamic Republic of", "+98", "IRR"),
  CountryModel("IS", "Iceland", "+354", "ISK"),
  CountryModel("IT", "Italy", "+39", "EUR"),
  CountryModel("JE", "Jersey", "+44", "JEP"),
  CountryModel("JM", "Jamaica", "+1", "JMD"),
  CountryModel("JO", "Jordan", "+962", "JOD"),
  CountryModel("JP", "Japan", "+81", "JPY"),
  CountryModel("KE", "Kenya", "+254", "KES"),
  CountryModel("KG", "Kyrgyzstan", "+996", "KGS"),
  CountryModel("KH", "Cambodia", "+855", "KHR"),
  CountryModel("KI", "Kiribati", "+686", "AUD"),
  CountryModel("KM", "Comoros", "+269", "KMF"),
  CountryModel("KN", "Saint Kitts and Nevis", "+1", "XCD"),
  CountryModel("KP", "North Korea", "+850", "KPW"),
  CountryModel("KR", "South Korea", "+82", "KRW"),
  CountryModel("KW", "Kuwait", "+965", "KWD"),
  CountryModel("KY", "Cayman Islands", "+345", "KYD"),
  CountryModel("KZ", "Kazakhstan", "+7", "KZT"),
  CountryModel("LA", "Lao People's Democratic Republic", "+856", "LAK"),
  CountryModel("LB", "Lebanon", "+961", "LBP"),
  CountryModel("LC", "Saint Lucia", "+1", "XCD"),
  CountryModel("LI", "Liechtenstein", "+423", "CHF"),
  CountryModel("LK", "Sri Lanka", "+94", "LKR"),
  CountryModel("LR", "Liberia", "+231", "LRD"),
  CountryModel("LS", "Lesotho", "+266", "LSL"),
  CountryModel("LT", "Lithuania", "+370", "LTL"),
  CountryModel("LU", "Luxembourg", "+352", "EUR"),
  CountryModel("LV", "Latvia", "+371", "LVL"),
  CountryModel("LY", "Libyan Arab Jamahiriya", "+218", "LYD"),
  CountryModel("MA", "Morocco", "+212", "MAD"),
  CountryModel("MC", "Monaco", "+377", "EUR"),
  CountryModel("MD", "Moldova, Republic of", "+373", "MDL"),
  CountryModel("ME", "Montenegro", "+382", "EUR"),
  CountryModel("MF", "Saint Martin", "+590", "EUR"),
  CountryModel("MG", "Madagascar", "+261", "MGA"),
  CountryModel("MH", "Marshall Islands", "+692", "USD"),
  CountryModel("MK", "Republic of North Macedonia", "+389", "MKD"),
  CountryModel("ML", "Mali", "+223", "XOF"),
  CountryModel("MM", "Myanmar", "+95", "MMK"),
  CountryModel("MN", "Mongolia", "+976", "MNT"),
  CountryModel("MO", "Macao", "+853", "MOP"),
  CountryModel("MP", "Northern Mariana Islands", "+1", "USD"),
  CountryModel("MQ", "Martinique", "+596", "EUR"),
  CountryModel("MR", "Mauritania", "+222", "MRO"),
  CountryModel("MS", "Montserrat", "+1", "XCD"),
  CountryModel("MT", "Malta", "+356", "EUR"),
  CountryModel("MU", "Mauritius", "+230", "MUR"),
  CountryModel("MV", "Maldives", "+960", "MVR"),
  CountryModel("MW", "Malawi", "+265", "MWK"),
  CountryModel("MX", "Mexico", "+52", "MXN"),
  CountryModel("MY", "Malaysia", "+60", "MYR"),
  CountryModel("MZ", "Mozambique", "+258", "MZN"),
  CountryModel("NA", "Namibia", "+264", "NAD"),
  CountryModel("NC", " Caledonia", "+687", "XPF"),
  CountryModel("NE", "Niger", "+227", "XOF"),
  CountryModel("NF", "Norfolk Island", "+672", "AUD"),
  CountryModel("NG", "Nigeria", "+234", "NGN"),
  CountryModel("NI", "Nicaragua", "+505", "NIO"),
  CountryModel("NL", "Netherlands", "+31", "EUR"),
  CountryModel("NO", "Norway", "+47", "NOK"),
  CountryModel("NP", "Nepal", "+977", "NPR"),
  CountryModel("NR", "Nauru", "+674", "AUD"),
  CountryModel("NU", "Niue", "+683", "NZD"),
  CountryModel("NZ", " Zealand", "+64", "NZD"),
  CountryModel("OM", "Oman", "+968", "OMR"),
  CountryModel("PA", "Panama", "+507", "PAB"),
  CountryModel("PE", "Peru", "+51", "PEN"),
  CountryModel("PF", "French Polynesia", "+689", "XPF"),
  CountryModel("PG", "Papua  Guinea", "+675", "PGK"),
  CountryModel("PH", "Philippines", "+63", "PHP"),
  CountryModel("PK", "Pakistan", "+92", "PKR"),
  CountryModel("PL", "Poland", "+48", "PLN"),
  CountryModel("PM", "Saint Pierre and Miquelon", "+508", "EUR"),
  CountryModel("PN", "Pitcairn", "+872", "NZD"),
  CountryModel("PR", "Puerto Rico", "+1", "USD"),
  CountryModel("PS", "Palestinian Territory, Occupied", "+970", "ILS"),
  CountryModel("PT", "Portugal", "+351", "EUR"),
  CountryModel("PW", "Palau", "+680", "USD"),
  CountryModel("PY", "Paraguay", "+595", "PYG"),
  CountryModel("QA", "Qatar", "+974", "QAR"),
  CountryModel("RE", "Reunion", "+262", "EUR"),
  CountryModel("RO", "Romania", "+40", "RON"),
  CountryModel("RS", "Serbia", "+381", "RSD"),
  CountryModel("RU", "Russia", "+7", "RUB"),
  CountryModel("RW", "Rwanda", "+250", "RWF"),
  CountryModel("SA", "Saudi Arabia", "+966", "SAR"),
  CountryModel("SB", "Solomon Islands", "+677", "SBD"),
  CountryModel("SC", "Seychelles", "+248", "SCR"),
  CountryModel("SD", "Sudan", "+249", "SDG"),
  CountryModel("SE", "Sweden", "+46", "SEK"),
  CountryModel("SG", "Singapore", "+65", "SGD"),
  CountryModel(
    "SH",
    "Saint Helena, Ascension and Tristan Da Cunha",
    "+290",
    "SHP",
  ),
  CountryModel("SI", "Slovenia", "+386", "EUR"),
  CountryModel("SJ", "Svalbard and Jan Mayen", "+47", "NOK"),
  CountryModel("SK", "Slovakia", "+421", "EUR"),
  CountryModel("SL", "Sierra Leone", "+232", "SLL"),
  CountryModel("SM", "San Marino", "+378", "EUR"),
  CountryModel("SN", "Senegal", "+221", "XOF"),
  CountryModel("SO", "Somalia", "+252", "SOS"),
  CountryModel("SR", "Suriname", "+597", "SRD"),
  CountryModel("SS", "South Sudan", "+211", "SSP"),
  CountryModel("ST", "Sao Tome and Principe", "+239", "STD"),
  CountryModel("SV", "El Salvador", "+503", "SVC"),
  CountryModel("SX", "Sint Maarten", "+1", "ANG"),
  CountryModel("SY", "Syrian Arab Republic", "+963", "SYP"),
  CountryModel("SZ", "Swaziland", "+268", "SZL"),
  CountryModel("TC", "Turks and Caicos Islands", "+1", "USD"),
  CountryModel("TD", "Chad", "+235", "XAF"),
  CountryModel("TF", "French Southern Territories", "+262", "EUR"),
  CountryModel("TG", "Togo", "+228", "XOF"),
  CountryModel("TH", "Thailand", "+66", "THB"),
  CountryModel("TJ", "Tajikistan", "+992", "TJS"),
  CountryModel("TK", "Tokelau", "+690", "NZD"),
  CountryModel("TL", "Timor-Leste", "+670", "USD"),
  CountryModel("TM", "Turkmenistan", "+993", "TMT"),
  CountryModel("TN", "Tunisia", "+216", "TND"),
  CountryModel("TO", "Tonga", "+676", "TOP"),
  CountryModel("TR", "Turkey", "+90", "TRY"),
  CountryModel("TT", "Trinidad and Tobago", "+1", "TTD"),
  CountryModel("TV", "Tuvalu", "+688", "AUD"),
  CountryModel("TW", "Taiwan", "+886", "TWD"),
  CountryModel("TZ", "Tanzania, United Republic of", "+255", "TZS"),
  CountryModel("UA", "Ukraine", "+380", "UAH"),
  CountryModel("UG", "Uganda", "+256", "UGX"),
  CountryModel("UM", "U.S. Minor Outlying Islands", "+1", "USD"),
  CountryModel("US", "United States of America", "+1", "USD"),
  CountryModel("UY", "Uruguay", "+598", "UYU"),
  CountryModel("UZ", "Uzbekistan", "+998", "UZS"),
  CountryModel("VA", "Holy See (Vatican City State)", "+379", "EUR"),
  CountryModel("VC", "Saint Vincent and the Grenadines", "+1", "XCD"),
  CountryModel("VE", "Venezuela, Bolivarian Republic of", "+58", "VEF"),
  CountryModel("VG", "Virgin Islands", "+1", "USD"),
  CountryModel("VI", "Virgin Islands, U.S.", "+1", "USD"),
  CountryModel("VN", "Vietnam", "+84", "VND"),
  CountryModel("VU", "Vanuatu", "+678", "VUV"),
  CountryModel("WF", "Wallis and Futuna", "+681", "XPF"),
  CountryModel("WS", "Samoa", "+685", "WST"),
  CountryModel("XK", "Kosovo", "+383", "EUR"),
  CountryModel("YE", "Yemen", "+967", "YER"),
  CountryModel("YT", "Mayotte", "+262", "EUR"),
  CountryModel("ZA", "South Africa", "+27", "ZAR"),
  CountryModel("ZM", "Zambia", "+260", "ZMW"),
  CountryModel("ZW", "Zimbabwe", "+263", "USD"),
  CountryModel("NANP", "North Carolina", "+919", "USD"),
  // CountryModel("UK", "Zimbabwe", "+263", "USD"),
];

List<CountryModel> getCountryList() {
  return COUNTRIES;
}
